### ISSUE TITLE
GrantedPermissionsStateInitialPage Pfeile falsch

### ISSUE THREAD

**Issue by fayddelight** [marcoseraphin/DelIt#1]
Die Pfeile sehen nicht so aus wie im Figma. 
Da komme ich auch bzgl Positionierung nicht weiter(Hot Reload funktioniert seit heute leider auch nicht mehr richtig).

**Comment by fayddelight** [comment]
![image](https://user-images.githubusercontent.com/66011598/139297585-b7f933d0-4193-48e2-acd2-f6afa983b3c2.png)

Siehe Image.

**Comment by marcoseraphin** [comment]
Antwort siehe meine eMail
