### ISSUE TITLE
GrantedPermissionsStateInitialPage Button

### ISSUE THREAD

**Issue by fayddelight** [marcoseraphin/DelIt#2]
![image](https://user-images.githubusercontent.com/66011598/139297241-7a4d8037-9811-406b-98b8-c849ae488720.png)

Unterstützt UTF-8 den QR-Code? Wie soll ich das machen?

**Comment by marcoseraphin** [comment]
Da brauchst Du nichts machen, die Programmierung der QR Code Komponente habe ich an einer anderen Stelle inkl. der recht komplexen System Berechtigungsanfragen bereits umgesetzt, das baue ich dann entsprechend ein, Du musst mir nur das Command im XAML und im ViewModel definieren.
